import { google } from 'googleapis';
import type { drive_v3 } from 'googleapis';

import { DEFAULT_GOOGLE_TIMEOUT_MS, withRetry, withTimeout } from '../googleRequest';
import type { LogContext } from '../logger';
import { time } from '../logger';
import type { TimelineExportModel } from './exportBuilder';

const buildDocBody = (model: TimelineExportModel) => {
  const lines: Array<{ text: string; style: 'TITLE' | 'HEADING_2' | null }> = [
    { text: model.title, style: 'TITLE' },
    { text: `Generated: ${new Date(model.generatedAt).toUTCString()}`, style: null },
    { text: `Artifacts: ${model.artifactCount}`, style: null },
    { text: '', style: null },
  ];

  model.groups.forEach((group) => {
    lines.push({ text: group.label, style: 'HEADING_2' });
    group.items.forEach((item) => {
      lines.push({ text: `• ${item.title}`, style: null });
      item.bullets.slice(0, 3).forEach((bullet) => lines.push({ text: `  - ${bullet}`, style: null }));
      if (item.sourceLabel) {
        lines.push({ text: `  Source: ${item.sourceLabel}`, style: null });
      }
    });
    lines.push({ text: '', style: null });
  });

  lines.push({ text: 'Generated by Timeline', style: null });

  let index = 1;
  const text = `${lines.map((line) => line.text).join('\n')}\n`;
  const styles = lines
    .map((line) => {
      const start = index;
      const end = start + line.text.length;
      index = end + 1;
      return { start, end, style: line.style };
    })
    .filter((line): line is { start: number; end: number; style: 'TITLE' | 'HEADING_2' } => Boolean(line.style));

  return { text, styles };
};

export const createTimelineDriveDoc = async ({
  drive,
  accessToken,
  folderId,
  model,
  ctx,
}: {
  drive: drive_v3.Drive;
  accessToken: string;
  folderId: string;
  model: TimelineExportModel;
  ctx?: LogContext;
}) => {
  const createOperation = () =>
    withRetry(
      (signal) =>
        withTimeout(
          (timeoutSignal) =>
            drive.files.create(
              {
                requestBody: {
                  name: `${model.title} - ${new Date(model.generatedAt).toISOString().slice(0, 10)}`,
                  mimeType: 'application/vnd.google-apps.document',
                  parents: [folderId],
                },
                fields: 'id, webViewLink',
              },
              { signal: timeoutSignal },
            ),
          DEFAULT_GOOGLE_TIMEOUT_MS,
          'upstream_timeout',
          signal,
        ),
      { ctx },
    );

  const created = ctx ? await time(ctx, 'drive.files.create.timeline_doc', createOperation) : await createOperation();
  const docId = created.data.id;
  if (!docId) {
    throw new Error('Unable to create document.');
  }

  const auth = new google.auth.OAuth2();
  auth.setCredentials({ access_token: accessToken });
  const docs = google.docs({ version: 'v1', auth });
  const { text, styles } = buildDocBody(model);

  const batchOperation = () =>
    withRetry(
      (signal) =>
        withTimeout(
          (timeoutSignal) =>
            docs.documents.batchUpdate(
              {
                documentId: docId,
                requestBody: {
                  requests: [
                    { insertText: { location: { index: 1 }, text } },
                    ...styles.map((style) => ({
                      updateParagraphStyle: {
                        range: { startIndex: style.start, endIndex: style.end },
                        paragraphStyle: { namedStyleType: style.style },
                        fields: 'namedStyleType',
                      },
                    })),
                  ],
                },
              },
              { signal: timeoutSignal },
            ),
          DEFAULT_GOOGLE_TIMEOUT_MS,
          'upstream_timeout',
          signal,
        ),
      { ctx },
    );

  if (ctx) {
    await time(ctx, 'docs.documents.batchUpdate.timeline_doc', batchOperation);
  } else {
    await batchOperation();
  }

  return {
    docId,
    webViewLink: created.data.webViewLink ?? `https://docs.google.com/document/d/${docId}/edit`,
  };
};
