import PDFDocument from 'pdfkit';

import type { TimelineExportModel } from './exportBuilder';

const PAGE_MARGIN = 50;

export const renderTimelinePdf = async (model: TimelineExportModel): Promise<Buffer> =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: PAGE_MARGIN, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(22).text(model.title);
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#4b5563').text(`Generated: ${new Date(model.generatedAt).toUTCString()}`);
    doc.text(`Artifacts: ${model.artifactCount}`);
    doc.moveDown(1);

    model.groups.forEach((group) => {
      doc.fillColor('#111827').fontSize(14).text(group.label);
      doc.moveDown(0.35);

      group.items.forEach((item) => {
        doc.fontSize(12).fillColor('#111827').text(item.title);
        item.bullets.slice(0, 3).forEach((bullet) => {
          doc.fontSize(10).fillColor('#1f2937').text(`• ${bullet}`, { indent: 14 });
        });
        if (item.sourceLabel) {
          doc.fontSize(9).fillColor('#6b7280').text(`Source: ${item.sourceLabel}`);
        }
        doc.moveDown(0.5);
      });

      doc.moveDown(0.5);
    });

    const footerY = doc.page.height - PAGE_MARGIN;
    doc.fontSize(9).fillColor('#6b7280').text('Generated by Timeline', PAGE_MARGIN, footerY, {
      align: 'center',
      width: doc.page.width - PAGE_MARGIN * 2,
    });

    doc.end();
  });
